Upgrade Django
azavea/pfb-network-connectivity pull request #961
Opened 2024-12-10 13:01 UTC by aaronxsu

## Overview

This PR upgrades Django and some related dependencies.

## Testing Instructions

- [ ] `./scripts/update` works fine
- [ ] `./scripts/test` runs fine
- [ ] `./scripts/server` spins up the app fine
- [ ] Use local dev data to test the app following UAT if any
   - [ ] Test places search page filtering
   - [ ] Test place detail page display
   - [ ] Test place detail page file download - this did not work for me, see [more details](https://github.com/azavea/pfb-network-connectivity/pull/962#issuecomment-2546545511)
   - [ ] Select more than 1 place and test the compare page
- I tested the above. There might be other frontend paths to test that I am not aware of. If there is any, please add them below, and we could use them as a starting point for a rough UAT:
   - [ ] a new test instruction...

## Checklist

- [ ] Add entry to CHANGELOG.md

Resolves https://github.com/azavea/pfb-network-connectivity/issues/957

2024-12-17 21:22 UTC, KlaasH requested changes
This looks good so far.  I put a few questions and comments below.  One thing I noticed was that when the update script runs migrations, it says:
> Your models in app(s): 'pfb_analysis', 'users' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

My guess is that there's something like a change to how a field type works.  I didn't go looking, but I would expect whatever it is to have an entry in the Django changelog with some description of why it changed and whether it requires any actual data changes or if the migration is just to keep the models in sync with the tables.

2024-12-19 21:44 UTC, aaronxsu commented on src/django/Dockerfile
> +RUN apt-get purge -y --auto-remove $buildDeps
I made the changes based on what's in [the project template](https://github.com/azavea/azavea-project-template/blob/develop/src/django/Dockerfile). I don't have strong preference on either solution.

2024-12-19 21:49 UTC, aaronxsu commented on src/django/Dockerfile
> -     "pfb_network_connectivity.wsgi"]
Similar to the above, this was to align with what the [project template](https://github.com/azavea/azavea-project-template/blob/develop/src/django/gunicorn.conf.py) does.

I don't have context regarding the reason for `gevent` in there, but we could add the following to the `gunicorn.conf.py`. Some sources might be helpful: 

```
```

2024-12-19 21:59 UTC, aaronxsu commented
@KlaasH Thanks for the review! I made the following two changes:

- https://github.com/azavea/pfb-network-connectivity/pull/961/commits/797b61f7c1cfd2b483cda0a62dccc0fd0deb2d3f: aligns the dev environment name in `gunicorn.config.py`
- https://github.com/azavea/pfb-network-connectivity/pull/961/commits/839d5a2065c88399251f27fdc19874cdc42b5cbc: adds two migrations per suggested- I am not sure about the impact of these two migrations. Could you please check and see if there is any issue before applying them?

I responded two of your comments and asked for your thoughts- please let me know and I will make changes.

2024-12-20 18:41 UTC, KlaasH commented on src/django/Dockerfile
> +RUN apt-get purge -y --auto-remove $buildDeps
Interesting.  I thought chaining them was standard practice and would have expected the project template to do it that way.  It looks like it did, but was changed in [024ba06](https://github.com/azavea/civic-apps-app-template/commit/024ba060a61bcbb4568b067233a0e1b7e896ea2c) with the comment "Cleanup the dockerfile so it has less chained commands (easier to debug this way)"

I won't argue that chained is easier to debug, but I'm not sure Bryan realized how much of a difference it makes in the image size.  Or maybe he did and thought it was worth it, but I think it makes more sense to keep it chained and let people break it up locally if they need to for debugging.

I built this container both ways—as 3 separate commands and with them chained into one—and the image size was 1.56GB for the former, 901MB for the latter.  That seems like a good enough argument for going with the chained command.

2024-12-20 18:44 UTC, KlaasH commented on src/django/Dockerfile
> -     "pfb_network_connectivity.wsgi"]
Yeah, adding `worker_class = 'gevent'` sounds good to me.

2024-12-20 18:46 UTC, aaronxsu commented on src/django/Dockerfile
> +RUN apt-get purge -y --auto-remove $buildDeps
OK. So it sounds like we are chaining all three of them into one.

2024-12-20 19:12 UTC, aaronxsu commented on src/django/Dockerfile
> +RUN apt-get purge -y --auto-remove $buildDeps
Changed in https://github.com/azavea/pfb-network-connectivity/pull/961/commits/e0ea15152d8745112c0248041a3413dcc7b6bdee

2024-12-20 19:12 UTC, aaronxsu commented on src/django/Dockerfile
> -     "pfb_network_connectivity.wsgi"]
Changed in https://github.com/azavea/pfb-network-connectivity/pull/961/commits/e0ea15152d8745112c0248041a3413dcc7b6bdee

2024-12-20 19:12 UTC, aaronxsu commented
Update, re: 
>I am not sure about the impact of these two migrations. Could you please check and see if there is any issue before applying them?

I applied the changes locally and running the app seems fine to me.

2024-12-20 19:59 UTC, aaronxsu commented
I rebased on top of `develop` branch after the merge of the fixture PR.

2024-12-20 20:01 UTC, KlaasH commented
> I am not sure about the impact of these two migrations

Turns out the answer is "none", which I think is actually somewhat common for Django upgrade migrations when using Postgres.  The migration system supports multiple database engines, and they don't all define the same table/column/etc properties, so sometimes a migration will be required because it's needed for one engine (e.g. MySQL or SQLite) but it's not a change that requires a migration for another engine.

The `sqlmigrate` management command is handy for finding out when that's the case, as it is here:
![image](https://github.com/user-attachments/assets/3a6868c4-ec0e-4a25-844a-9fb20846ff8d)

So yeah, we need these migrations to avoid getting yelled at by the migration system, but for our purposes, they don't actually do anything.

2024-12-20 20:59 UTC, KlaasH reviewed
I think this is likely fine—everything I've tested via the front end is working, and I don't know of any reason to think there are subtle issues waiting to bite us just beyond the reaches of those tests—but I'd like to run at least one full analysis before calling it good, and I haven't managed to do so.  My Vagrant environment is not working at the moment, which hasn't bothered me because docker-on-host has been working well for the app and we don't want to keep using Vagrant anyway, but I have not succeeded in running a a docker-on-host analysis.  I think it's likely a matter of just sorting out a few more environment variables, but yeah, I haven't gotten there yet.

We've talked about removing Vagrant but haven't made an issue for it yet.  I'm not sure if it makes sense to make a self-contained issue for that then come back to this once the analysis-on-host is sorted, or if I should just work through the issues locally to get this issue to the finish line and fold that work into a "get rid of Vagrant" issue later on.  Either way it'll have to be after the holidays.

2025-02-17 21:04 UTC, KlaasH approved these changes
Ok, I got my branch for #964 (feature/kjh/remove-vagrant) working and cherry-picked this commit onto it to confirm that I could still run the analysis locally.
It worked fine, so this is good to go :+1:

2025-02-18 16:03 UTC, aaronxsu commented
Thanks for the review. I updated changelog and will merge.

2025-02-18 16:08 UTC, merged